### ISSUE TITLE
template design

### ISSUE THREAD

**Issue by toufik1998** [toufik1998/Invitation-landing-page#6]
Create design of sign in and sign up pages

**Comment by SuperGhostSama** [comment]
Completed the Sign up https://www.figma.com/file/I2cQd28BxHczNM5o5g4ZtF/Sign-Up-(Community)?node-id=0%3A1
Completed the Log In https://www.figma.com/file/gWyt19LyKrAp4EJZ5kSxH7/Sign-In-(Community)?node-id=0%3A1
